language: node_js
node_js:
  - '8'
  - '10'
before_script:
  - export DISPLAY=:99.0
services:
  - xvfb
install:
  - npm install
  - gulp build
script:
  - npm test
after_success:
  - npm run test:coverage
  - 'npm install coveralls && cat ./coverage/lcov.info | coveralls'
